server:
  port: 8889
spring:
  application:
    name: config-server-git
  cloud:
    config:
      server:
        git:
          uri: ${GIT_CONFIG_PROJECT}
          default-label: master
          skip-ssl-validation: true
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}