version: '3.1'

### mongo compose ###
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: root
      MONOGO_INITDB_DATABASE: case
    ports:
      - "27010:27017"
    volumes:
      - ./data:/data/db



