server:
  port: 8889
spring:
  zipkin:
    enabled: true
    base-url: http://10.108.5.92:9411
    service:
      name: git-config-service
  application:
    name: config-server-git
  cloud:
    config:
      server:
        git:
          uri: ${GIT_URI}
          default-label: main
          skip-ssl-validation: true
          username: ${GIT_USERNAME}
          password: ${GIT_TOKEN_KEY}