server:
  port: 7071

spring:
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/Java10SocialUser
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update