apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastic-deployment
spec:
  selector:
    matchLabels:
      app: elastic-app
  template:
    metadata:
      labels:
        app: elastic-app
    spec:
      containers:
        - name: container-elastic
          image: elasticsearch:7.17.12
          resources:
            limits:
              memory: "1024Mi"
              cpu: "250m"
          ports:
            - containerPort: 9200
              name: elasticone
            - containerPort: 9300
              name: elastictwo
          env:
            - name: discovery.type
              value: single_node
            - name: xpack.security.enabled
              value: "false"
