apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin-deployment
spec:
  selector:
    matchLabels:
      app: zipking-app
  template:
    metadata:
      labels:
        app: zipking-app
    spec:
      containers:
        - name: container-zipkin
          image: openzipkin/zipkin
          resources:
            limits:
              memory: "256Mi"
              cpu: "100m"
          ports:
            - containerPort: 9411
