apiVersion: v1
kind: Service
metadata:
  name: elastic-cluster
spec:
  selector:
    app: elastic-app
  type: ClusterIP
  ports:
    - port: 9200
      targetPort: 9200
      name: elasticserviceone
    - port: 9300
      targetPort: 9300
      name: elasticservicetwo
