apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-cluster
spec:
  selector:
    app: rabbitmq-app
  type: ClusterIP
  ports:
    - port: 5672
      targetPort: 5672
      name: rabbitmq-api
    - port: 15672
      targetPort: 15672
      name: rabbitmq-web
