server:
  port: 7072
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: 123456789

  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: auth-service
  datasource:
    username: postgres
    password: 123456789
    url: jdbc:postgresql://localhost:5432/socialUser1
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

jwt:
  secretKey: ${JAVA_SECRETKEY}
  issuer: ${JAVA_ISSUER}
rabbitmq:
  register-queue: register-queue
  activation-queue: queue-activation
redis:
  host: localhost
  port: 6379
