server:
  port: 7072
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: 123456789

  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: auth-service
  data:
    mongodb:
      host: localhost
      port: 27017
      username: java10user
      password: root
      database: userDb


jwt:
  secretKey: ${JAVA_SECRETKEY}
  issuer: ${JAVA_ISSUER}
rabbitmq:
  register-queue: register-queue
  activation-queue: queue-activation
  register-elastic-queue: register-elastic-queue
  user-exchange: user-exchange
  register-elastic-binding-key: register-elastic-binding-key
redis:
  host: localhost
  port: 6379
