server:
  port: 7072
spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: user-service
  datasource:
    username: postgres
    password: 123456789
    url: jdbc:postgresql://localhost:5432/Java10SocialUser
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
jwt:
  secretKey: ${JAVA_SECRETKEY}
  issuer: ${JAVA_ISSUER}