version: '3.1'

networks:
  java_10_network:
    driver: bridge

services:
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: sabah_zipkin
    ports:
      - "9411:9411"
    networks:
      - java_10_network
  rabbitmq:
    image: rabbitmq:3-management
    container_name: sabah_rabbitmq
    environment:
        - RABBITMQ_DEFAULT_USER=user
        - RABBITMQ_DEFAULT_PASS=123456789
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - java_10_network
  redis:
    image: redis:latest
    container_name: sabah_redis
    ports:
      - "6379:6379"
    networks:
      - java_10_network
  elasticsearch:
    image: elasticsearch:7.17.12
    container_name: sabah_es01
    environment:
      - discovery.type=single-node
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" deploysuzda böyle limit veriliyodu
      - xpack.security.enabled=false
    ports:
      - 9200:9200
      - 9300:9300
    deploy:
        resources:
            limits:
              cpus: "0.50"
              memory: 512M
            reservations:
              cpus: "0.25"
              memory: 256M

    networks:
      - java_10_network
  kibana:
    container_name: kibana
    image: kibana:7.17.12
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200    # address of elasticsearch docker container which kibana will connect
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
        - java_10_network