server:
  port: 7070

spring:
  datasource:
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://localhost:5432/Java10SocialAuth
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

jwt:
  secretKey: ${JAVA_SECRETKEY}
  issuer: ${JAVA_ISSUER}
